name: Build Daison

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-10.15, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python3 -m pip install git+https://github.com/joerick/cibuildwheel.git@main

    - name: Install twine
      run: pip install twine

    - name: Compile the package
      run: |
        python3 -m cibuildwheel . --output-dir wheelhouse

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: daison-${{ matrix.os }}
        path: ./wheelhouse

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - uses: actions/download-artifact@master
      with:
        name: daison-ubuntu-latest
        path: ./dist

    - uses: actions/download-artifact@master
      with:
        name: daison-macos-10.15
        path: ./dist

    - uses: actions/download-artifact@master
      with:
        name: daison-windows-latest
        path: ./dist

    - name: Publish
      env:
        TWINE_USERNAME: krasimir
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        (curl -I --fail https://pypi.org/project/$(python setup.py --name)/$(python setup.py --version)/) || twine upload dist/*
