name: Build Daison

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python3 -m pip install git+https://github.com/joerick/cibuildwheel.git@main

    - name: Compile the package
      run: |
        python3 -m cibuildwheel . --output-dir wheelhouse

    - uses: actions/upload-artifact@master
      with:
        name: daison-${{ matrix.os }}
        path: ./wheelhouse
