name: Build Daison

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-10.15, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: |
        python3 -m pip install git+https://github.com/joerick/cibuildwheel.git@main

    - name: Compile the package
      run: |
        python3 -m cibuildwheel . --output-dir wheelhouse

    - name: Publish
      env: |
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        (curl -I --fail https://pypi.org/project/$(python setup.py --name)/$(python setup.py --version)/) || twine upload wheelhouse/*
